文件原数据读取
paion-data/athena pull request #39
Opened 2024-04-17 10:25 UTC by A-Little-Excited

## Changelog

### Added
新增对 MetaServlet 的 Spring 封装

### Changed

### Deprecated

### Removed

### Fixed

### Security

## Checklist

- [ ] Test
- [ ] Self-review
- [ ] Documentation

2024-04-18 02:05 UTC, A-Little-Excited commented on athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/config/FileConfigSpec.groovy
没有进行重写，是将文件名从 beanConfig 修改为了 fileConfig，感觉之前的命名不是很好

2024-04-22 07:17 UTC, QubitPi requested changes

2024-04-22 07:17 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/pom.xml
> +            <artifactId>spring-boot-starter-webflux</artifactId>
为什么会引入 webflux?

2024-04-22 07:17 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/pom.xml
> +        </dependency>
用 bom

2024-04-22 07:17 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/FileConfig.java
> +public class FileConfig {
FileConfig 听起来像是文件配置，而非文件接口配置

2024-04-22 07:17 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/src/main/java/com/paiondata/athena/spring/boot/autoconfigure/config/MetaConfig.java
> +public class MetaConfig {
同 FileConfig

2024-04-24 08:27 UTC, QubitPi reviewed
大体上没有问题

2024-04-24 08:27 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/pom.xml
> +            <scope>test</scope>
不需要 ` <scope>test</scope>`，顶级 pom 已经制定 ` <scope>test</scope>` 了

2024-04-24 08:27 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/pom.xml
> +            <scope>test</scope>
不需要 `<scope>test</scope>`

2024-04-24 08:27 UTC, QubitPi commented on athena-spring/athena-spring-boot-autoconfigure/src/test/groovy/com/paiondata/athena/spring/boot/autoconfigure/database/DerbyDataSourceProvider.groovy
删掉

2024-04-24 10:05 UTC, merged